# Generated by Django 5.0.7 on 2024-09-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=3000)),
                ('name2', models.CharField(blank=True, max_length=3000, null=True)),
                ('model', models.CharField(blank=True, max_length=3000, null=True)),
                ('price', models.CharField(max_length=3000)),
                ('date_added', models.CharField(max_length=3000)),
                ('city', models.CharField(blank=True, max_length=3000, null=True)),
                ('km_worked', models.CharField(max_length=3000)),
                ('details', models.CharField(blank=True, max_length=3000, null=True)),
                ('link', models.CharField(max_length=3000, unique=True)),
                ('link2', models.CharField(max_length=3000)),
                ('image', models.CharField(max_length=3000)),
            ],
        ),
    ]
