# Generated by Django 5.0.7 on 2024-09-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='link2',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
