# Generated by Django 5.0.7 on 2024-09-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0002_alter_car_link2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name2',
        ),
    ]
